name = "DecisionProgramming"
uuid = "0e836bf4-a496-11ea-2c13-edcbe498ce6b"
authors = ["Jaan Tollander de Balsch <dev@jaantollander.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = ">=1.1"
JuMP = ">=0.21"
Parameters = ">=0.12"
